2022-01-25 09:31:01 ERROR Thresh-Server-Test main com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine request fail. non tx-manager is alive. on reportInvalidTM.
2022-01-25 09:31:01 ERROR Thresh-Server-Test main org.springframework.boot.SpringApplication Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.zhang.thresh.server.test.ThreshServerTestApplication.main(ThreshServerTestApplication.java:19)
Caused by: java.lang.IllegalStateException: There is no normal TM.
	at com.codingapi.txlcn.tc.txmsg.TMSearcher.search(TMSearcher.java:86)
	at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.prepareToResearchTMCluster(AutoTMClusterEngine.java:83)
	at com.codingapi.txlcn.tc.txmsg.AutoTMClusterEngine.onConnectFail(AutoTMClusterEngine.java:69)
	at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.lambda$connectFail$3(TCSideRpcInitCallBack.java:107)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.codingapi.txlcn.tc.txmsg.TCSideRpcInitCallBack.connectFail(TCSideRpcInitCallBack.java:107)
	at com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer.connect(NettyRpcClientInitializer.java:125)
	at com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer.init(NettyRpcClientInitializer.java:85)
	at com.codingapi.txlcn.tc.txmsg.TCRpcServer.init(TCRpcServer.java:58)
	at com.codingapi.txlcn.common.runner.TxLcnApplicationRunner.run(TxLcnApplicationRunner.java:54)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	... 5 common frames omitted
2022-01-25 12:38:51 ERROR Thresh-Server-Test nioEventLoopGroup-2-1 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler NettyClientRetryHandler - exception . 
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:378)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2022-01-25 12:38:51 ERROR Thresh-Server-Test nioEventLoopGroup-2-1 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler keepSize:1,nowSize:0
2022-01-25 12:38:51 ERROR Thresh-Server-Test nioEventLoopGroup-2-1 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler socketAddress:/0.0.0.0:8888 
